repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.78.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
        exclude: CHAP02/version|CHAP06/validate
      - id: terraform_tfsec
        args:
         - --args=--config-file=__GIT_WORKING_DIR__/.tfsec/config.yml  --ignore-hcl-errors