repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.78.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        exclude: CHAP07/privatemodule|CHAP12/preventdestroy/
      - id: terraform_validate
        exclude: CHAP02/version|CHAP06/validate|CHAP07/privatemodule|CHAP07/moduledemo/myapp-loop
      - id: terraform_tfsec
        exclude: CHAP07/privatemodule
        args:
         - --args=--config-file=__GIT_WORKING_DIR__/.tfsec/config.yml  --ignore-hcl-errors