name: 'Terraform'

working-directory: ./CHAP12/cert/

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write


jobs: 
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: dev 
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      run: terraform init